package dev.createarsenal.beacon;

import net.minecraft.core.*;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.gametest.framework.*;
import net.minecraft.nbt.*;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.*;
import net.minecraft.world.item.*;
import net.minecraft.world.item.context.*;
import net.minecraft.world.level.*;
import net.minecraft.world.level.block.*;
import net.minecraft.world.phys.*;
import net.minecraftforge.gametest.GameTestHolder;
import java.util.*;

@GameTestHolder(ArsenalBeacon.ID)
@net.minecraftforge.gametest.PrefixGameTestTemplate(false)
public final class DisplayRackGameTests {
    private static ItemStack gun()throws Exception{var item=BuiltInRegistries.ITEM.get(new ResourceLocation("tacz:modern_kinetic_gun"));var gun=new ItemStack(item);item.getClass().getMethod("setGunId",ItemStack.class,ResourceLocation.class).invoke(item,gun,new ResourceLocation("tacz:ak47"));gun.getOrCreateTag().putInt("GunCurrentAmmoCount",7);gun.getOrCreateTag().putBoolean("Jammed",true);gun.getOrCreateTag().putString("TestAttachment","preserved");gun.setDamageValue(17);gun.setHoverName(net.minecraft.network.chat.Component.literal("Personal rifle"));return gun;}
    @GameTest(template="empty3x3x3",batch="racks015",timeoutTicks=100)
    public static void nativeGunPlacementSwapRetrievalAndPersistence(GameTestHelper h)throws Exception{
        var l=h.getLevel();var root=h.absolutePos(new BlockPos(1,1,1));var p=UpgradeGameTests.player(h,"racks015");p.setGameMode(GameType.SURVIVAL);var original=gun();
        for(var registry:ArsenalBeacon.RACKS){var state=registry.get().defaultBlockState();l.setBlock(root.south(),Blocks.STONE.defaultBlockState(),3);l.setBlock(root.east().south(),Blocks.STONE.defaultBlockState(),3);l.setBlock(root,state,3);var display=(dev.createarsenal.displays.DisplayRacks.DisplayEntity)l.getBlockEntity(root);p.getInventory().clearContent();p.setItemInHand(InteractionHand.MAIN_HAND,original.copy());var hit=new BlockHitResult(Vec3.atCenterOf(root),Direction.NORTH,root,false);state.use(l,p,InteractionHand.MAIN_HAND,hit);
            h.assertTrue(p.getMainHandItem().isEmpty()&&ItemStack.matches(display.gun(),original),"Rack consumes exactly one actual gun, retaining all NBT");var saved=display.saveWithFullMetadata();display.load(new CompoundTag());display.load(saved);h.assertTrue(ItemStack.matches(display.gun(),original)&&display.getUpdateTag().getCompound("Item").equals(saved.getCompound("Item")),"World persistence and update packet preserve complete gun item: original="+original.save(new CompoundTag())+" loaded="+display.gun().save(new CompoundTag())+" saved="+saved+" packet="+display.getUpdateTag());
            var replacement=original.copy();replacement.getOrCreateTag().putInt("GunCurrentAmmoCount",2);p.setItemInHand(InteractionHand.MAIN_HAND,replacement.copy());state.use(l,p,InteractionHand.MAIN_HAND,hit);h.assertTrue(ItemStack.matches(display.gun(),replacement)&&p.getInventory().items.stream().anyMatch(s->ItemStack.matches(s,original)),"Replacing a gun returns previous exact item without duplication");p.getInventory().clearContent();state.use(l,p,InteractionHand.MAIN_HAND,hit);h.assertTrue(display.gun().isEmpty()&&p.getInventory().items.stream().filter(s->ItemStack.matches(s,replacement)).count()==1,"Empty hand retrieves displayed gun exactly once");l.setBlock(root,Blocks.AIR.defaultBlockState(),3);
        }h.succeed();
    }
    @GameTest(template="empty3x3x3",batch="racks015",timeoutTicks=100)
    public static void wideRacksRotateReserveCellsAndMineExactlyOnce(GameTestHelper h)throws Exception{
        var l=h.getLevel();var floor=new BlockPos(7000,101,0);UpgradeGameTests.arena(l,floor);var root=floor.above();var p=UpgradeGameTests.player(h,"wide015");p.setGameMode(GameType.SURVIVAL);boolean drops=l.getGameRules().getBoolean(GameRules.RULE_DOBLOCKDROPS);l.getGameRules().getRule(GameRules.RULE_DOBLOCKDROPS).set(true,l.getServer());var capture=new RemodelGameTests.DropCapture(l,root);net.minecraftforge.common.MinecraftForge.EVENT_BUS.register(capture);
        try{for(var registered:ArsenalBeacon.RACKS){var block=(dev.createarsenal.displays.DisplayRacks.Rack)registered.get();if(!block.wide())continue;for(var facing:Direction.Plane.HORIZONTAL){var state=block.defaultBlockState().setValue(dev.createarsenal.displays.DisplayRacks.FACING,facing);var second=dev.createarsenal.displays.DisplayRacks.partner(root,state);l.setBlock(root.relative(facing.getOpposite()),Blocks.STONE.defaultBlockState(),3);l.setBlock(second.relative(facing.getOpposite()),Blocks.STONE.defaultBlockState(),3);l.setBlock(root,state,3);
                h.assertTrue(l.getBlockState(second).is(block)&&l.getBlockState(second).getValue(dev.createarsenal.displays.DisplayRacks.PART)&&dev.createarsenal.displays.DisplayRacks.anchor(l,second).equals(root)&&l.getBlockEntity(second)==null,"Wide partner forwards to anchor in every rotation and owns no second renderer");((dev.createarsenal.displays.DisplayRacks.DisplayEntity)l.getBlockEntity(root)).swap(gun());capture.items.clear();var part=l.getBlockState(second);part.getBlock().playerWillDestroy(l,second,part,p);l.setBlock(second,Blocks.AIR.defaultBlockState(),3);
                h.assertTrue(l.getBlockState(root).isAir()&&l.getBlockState(second).isAir()&&capture.items.stream().filter(i->i.getItem().is(block.asItem())).count()==1&&capture.items.stream().filter(i->dev.createarsenal.displays.DisplayRacks.isGun(i.getItem())).count()==1,"Mining the partner drops one rack and one exact gun");capture.items.forEach(net.minecraft.world.entity.Entity::discard);l.setBlock(root.relative(facing.getOpposite()),Blocks.AIR.defaultBlockState(),3);l.setBlock(second.relative(facing.getOpposite()),Blocks.AIR.defaultBlockState(),3);
            }}
            var block=(dev.createarsenal.displays.DisplayRacks.Rack)ArsenalBeacon.RACKS.get(2).get();p.setYRot(0);var second=root.east();l.setBlock(second,Blocks.CHEST.defaultBlockState(),3);var context=new BlockPlaceContext(l,p,InteractionHand.MAIN_HAND,new ItemStack(block),new BlockHitResult(Vec3.atCenterOf(root),Direction.UP,root,false));h.assertTrue(block.getStateForPlacement(context)==null&&l.getBlockState(second).is(Blocks.CHEST),"Occupied partner is rejected instead of overwriting a container");
        }finally{net.minecraftforge.common.MinecraftForge.EVENT_BUS.unregister(capture);l.getGameRules().getRule(GameRules.RULE_DOBLOCKDROPS).set(drops,l.getServer());UpgradeGameTests.release(l,floor);}h.succeed();
    }
    @GameTest(template="empty3x3x3",batch="racks015",timeoutTicks=100)
    public static void raidRepairsRestoreSpentGunStateWithoutDroppingInventory(GameTestHelper h)throws Exception{
        var l=h.getLevel();var root=h.absolutePos(new BlockPos(1,1,1));for(var registered:ArsenalBeacon.RACKS){var block=(dev.createarsenal.displays.DisplayRacks.Rack)registered.get();if(!block.glass()&&!block.wide())continue;var state=block.defaultBlockState();l.setBlock(root.south(),Blocks.STONE.defaultBlockState(),3);l.setBlock(root.east().south(),Blocks.STONE.defaultBlockState(),3);l.setBlock(root,state,3);var original=gun();((dev.createarsenal.displays.DisplayRacks.DisplayEntity)l.getBlockEntity(root)).swap(original);var second=block.wide()?dev.createarsenal.displays.DisplayRacks.partner(root,state):root;var d=new CampaignData();d.beacon=root.west(3);d.phase="raid";d.snapshot.put(root.asLong(),state);d.snapshot.put(second.asLong(),l.getBlockState(second));var capture=new RemodelGameTests.DropCapture(l,root);net.minecraftforge.common.MinecraftForge.EVENT_BUS.register(capture);
        try{ArsenalBeacon.damageBlock(l,d,second);h.assertTrue(l.getBlockState(root).isAir()&&l.getBlockState(second).isAir()&&d.damage.size()==1&&capture.items.isEmpty(),"Raid damage through partner journals one inventory and emits no gun drops");d.phase="restore";d.victoryRestoration=true;ArsenalBeacon.restore(l,d);h.assertTrue(ItemStack.matches(((dev.createarsenal.displays.DisplayRacks.DisplayEntity)l.getBlockEntity(root)).gun(),original)&&dev.createarsenal.displays.DisplayRacks.anchor(l,second).equals(root)&&l.getBlockState(second).is(state.getBlock()),"Repair restores spent ammo, durability tags and the full two-cell rack: original="+original.save(new CompoundTag())+" loaded="+((dev.createarsenal.displays.DisplayRacks.DisplayEntity)l.getBlockEntity(root)).gun().save(new CompoundTag())+" partner="+l.getBlockState(second));}finally{net.minecraftforge.common.MinecraftForge.EVENT_BUS.unregister(capture);}l.setBlock(root,Blocks.AIR.defaultBlockState(),3);}h.succeed();
    }
    @GameTest(template="empty3x3x3",batch="racks015",timeoutTicks=100)
    public static void allElevenDisplaysAreCraftableInSuppliesWithAnyPlanks(GameTestHelper h)throws Exception{
        var p=UpgradeGameTests.player(h,"supplies015");p.setGameMode(GameType.SURVIVAL);var root=h.absolutePos(new BlockPos(1,1,1));h.getLevel().setBlock(root,ArsenalBeacon.GUN_PLATFORM.get().defaultBlockState(),3);var entries=WeaponPlatform.specialEntries(p,"",9).stream().filter(DisplayRacks::entry).toList();h.assertTrue(entries.size()==11,"All eleven displays are in Supplies");
        for(var entry:entries){h.assertTrue(h.getLevel().getRecipeManager().byKey(new ResourceLocation("arsenal_displays",entry.recipeId().getPath())).isEmpty(),"Vanilla recipes are disabled when beacon mod is installed");h.assertTrue(CreateUnlocks.supply(entry)&&CreateUnlocks.required(entry)==0&&CreateUnlocks.unlocked(p,entry,1),"Display furniture is available independent of Age and Create milestones");p.getInventory().clearContent();var costs=WeaponPlatform.costs(entry);for(var cost:costs){ItemStack material=Arrays.stream(cost.ingredient().getItems()).anyMatch(s->s.is(Items.OAK_PLANKS))?new ItemStack(Items.BIRCH_PLANKS):cost.ingredient().getItems()[0].copy();p.getInventory().add(material.copyWithCount(cost.count()));}h.assertTrue(WeaponPlatform.craft(p,root,entry.recipeId()).startsWith("Crafted")&&p.getInventory().countItem(entry.output().getItem())==1,"Supplies recipe is paid atomically using birch rather than one special wood");}h.succeed();
    }
}
