"""The falling fire support ordnance: an artillery shell and the Bunker Buster bomb (block models drawn by the ordnance renderer),
their shared 32 x 32 texture, and the starshell's glow sprite. Deterministic; run from the repository root:
  python3 tools/ui-assets/ordnance_models.py
Both models stand nose down along +Y from y = 0 (the nose) so they fall tip first. The colour band of a shell has tintindex 0: the renderer
paints it in the fire support's own colour.
"""
import json, math, os
from PIL import Image, ImageDraw
from artlib import RAMPS, pick, hx

ROOT = 'custom-mods/arsenal-beacon/src/main/resources/assets/arsenal_beacon'
RAMPS['olive'] = [hx(c) for c in ('#1f2414', '#323a20', '#4a5530', '#647343', '#83935c', '#a8b67f')]
RAMPS['white'] = [hx(c) for c in ('#9aa0a6', '#b8bec4', '#d4d8dc', '#e8ebee', '#f6f7f8', '#ffffff')]
RAMPS['hazard'] = [hx(c) for c in ('#2a2400', '#5c4f00', '#a68b00', '#e0bb10', '#f8d838', '#fff07a')]


def texture():
    im = Image.new('RGBA', (32, 32), (0, 0, 0, 255)); d = ImageDraw.Draw(im)

    def tile(i, j, ramp, base, lines=False, rivets=False):
        x0, y0 = i * 8, j * 8
        for y in range(8):
            for x in range(8):
                v = base + 0.08 * math.sin(x * 1.7 + y * 0.9) + (0.12 if x == 0 else -0.1 if x == 7 else 0)
                if lines and x in (3,): v -= 0.15
                im.putpixel((x0 + x, y0 + y), pick(ramp, v))
        if rivets:
            for (x, y) in ((1, 1), (6, 1), (1, 6), (6, 6)):
                im.putpixel((x0 + x, y0 + y), pick('brass', .9))
    tile(0, 0, 'olive', .5, lines=True)       # shell / bomb body
    tile(1, 0, 'steel', .3)                   # nose
    tile(2, 0, 'white', .55)                  # colour band (tinted)
    tile(3, 0, 'copper', .55)                 # driving band
    for y in range(8):                        # hazard stripes
        for x in range(8):
            im.putpixel((x, 8 + y), pick('hazard', .7) if ((x + y) // 2) % 2 == 0 else pick('dark', .2))
    tile(1, 1, 'steel', .62, rivets=True)     # fins
    tile(2, 1, 'steel', .85)                  # hardened tip
    tile(3, 1, 'olive', .45, lines=True)      # bomb body with stencil
    for (x, y) in ((25, 10), (26, 10), (27, 10), (25, 12), (26, 12), (25, 11), (28, 12), (29, 12), (28, 10), (29, 11)):
        im.putpixel((x, y), pick('hazard', .85))
    return im


UV = {'body': (0, 0), 'nose': (1, 0), 'band': (2, 0), 'copper': (3, 0), 'hazard': (0, 1), 'fin': (1, 1), 'tip': (2, 1), 'stencil': (3, 1)}


def element(name, frm, to, part, tint=False, rot45=False):
    i, j = UV[part]; uv = [i * 4, j * 4, i * 4 + 4, j * 4 + 4]
    faces = {}
    for f in ('north', 'south', 'east', 'west', 'up', 'down'):
        face = {'uv': uv, 'texture': '#0'}
        if tint: face['tintindex'] = 0
        faces[f] = face
    e = {'name': name, 'from': list(frm), 'to': list(to), 'faces': faces}
    if rot45: e['rotation'] = {'origin': [8, 8, 8], 'axis': 'y', 'angle': 45}
    return e


def octagon(name, y0, y1, half, part, tint=False):
    lo, hi = 8 - half, 8 + half
    return [element(name, (lo, y0, lo), (hi, y1, hi), part, tint), element(name + ' (45)', (lo, y0, lo), (hi, y1, hi), part, tint, rot45=True)]


def model(elements):
    return {'credit': 'Eternal Defense - generated by tools/ui-assets/ordnance_models.py', 'ambientocclusion': False,
            'textures': {'0': 'arsenal_beacon:block/ordnance', 'particle': 'arsenal_beacon:block/ordnance'}, 'elements': elements}


def shell():
    e = []
    e += [element('Fuse', (7.25, 0, 7.25), (8.75, 1.5, 8.75), 'tip')]
    e += octagon('Ogive tip', 1.5, 3.5, 1.5, 'nose')
    e += octagon('Ogive', 3.5, 6, 2.4, 'nose')
    e += octagon('Body', 6, 15, 3, 'body')
    e += octagon('Colour band', 8, 9.5, 3.15, 'band', tint=True)
    e += octagon('Driving band', 12.5, 13.5, 3.2, 'copper')
    e += octagon('Base', 15, 16, 2.6, 'nose')
    return model(e)


def bomb():
    e = []
    e += [element('Penetrator tip', (6.75, 0, 6.75), (9.25, 2.5, 9.25), 'tip')]
    e += octagon('Nose', 2.5, 5.5, 2.6, 'nose')
    e += octagon('Nose shoulder', 5.5, 8.5, 3.6, 'nose')
    e += octagon('Body', 8.5, 25, 4, 'stencil')
    e += octagon('Warning band', 9.5, 11.5, 4.15, 'hazard')
    e += octagon('Colour band', 22, 23.5, 4.15, 'band', tint=True)
    e += octagon('Tail cone', 25, 28, 3, 'body')
    e += [element('Fin north-south', (7.6, 23, 1), (8.4, 32, 15), 'fin'), element('Fin east-west', (1, 23, 7.6), (15, 32, 8.4), 'fin')]
    e += [element('Fin ring', (2.5, 30.5, 2.5), (13.5, 31.5, 13.5), 'fin')]
    return model(e)


def star():
    im = Image.new('RGBA', (32, 32), (0, 0, 0, 0))
    for y in range(32):
        for x in range(32):
            d = math.hypot(x - 15.5, y - 15.5) / 15.5
            ray = max(0.0, 1 - abs(x - 15.5) / 1.6) * max(0, 1 - d) + max(0.0, 1 - abs(y - 15.5) / 1.6) * max(0, 1 - d)
            a = max(0.0, 1 - d) ** 2.2 + 0.6 * ray
            if a <= 0.01: continue
            core = max(0.0, 1 - d * 3)
            r, g, b = 255, int(235 + 20 * core), int(170 + 85 * core)
            im.putpixel((x, y), (r, g, b, int(min(1, a) * 255)))
    return im


if __name__ == '__main__':
    os.makedirs(f'{ROOT}/textures/block', exist_ok=True)
    texture().save(f'{ROOT}/textures/block/ordnance.png')
    star().save(f'{ROOT}/textures/entity/starshell.png')
    for name, fn in (('support_shell', shell), ('support_bomb', bomb)):
        with open(f'{ROOT}/models/block/{name}.json', 'w') as f:
            json.dump(fn(), f, indent=2); f.write('\n')
    print('ordnance models and textures written')
