modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="arsenal_beacon"
version="0.21.0"
displayName="Create Arsenal: Defense Beacon"
description='''A shared cooperative factory defense campaign with sparse night raids, industrial upgrades and journaled structural repairs.'''
[[dependencies.arsenal_beacon]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.arsenal_beacon]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.arsenal_beacon]]
modId="arsenal_displays"
mandatory=false
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.arsenal_beacon]]
modId="tacz"
mandatory=true
versionRange="[1.1.8,1.2)"
ordering="AFTER"
side="BOTH"

[[dependencies.arsenal_beacon]]
modId="create"
mandatory=true
versionRange="[6.0,7)"
ordering="AFTER"
side="BOTH"

[[dependencies.arsenal_beacon]]
modId="kubejs"
mandatory=true
versionRange="[2001,)"
ordering="AFTER"
side="BOTH"

[[dependencies.arsenal_beacon]]
modId="tacz_attributes"
mandatory=true
versionRange="[1.4]"
ordering="AFTER"
side="BOTH"

[[dependencies.arsenal_beacon]]
modId="lrtactical"
mandatory=false
versionRange="[0,)"
ordering="AFTER"
side="BOTH"
